import streamlit as st
import pandas as pd
import plotly.express as px
from pathlib import Path

# --- 1. SETUP & DATA LOADING ---
st.set_page_config(page_title="Statistical vs. Deterministic", layout="wide")

# Define the path to the artifact generated by your prep script
DATA_PATH = Path("data/app_data/player_db.csv")

@st.cache_data
def load_data():
    """
    Loads the static player database prepared by the deployment script.
    """
    if not DATA_PATH.exists():
        st.error(f"⚠️ Data file not found at {DATA_PATH}. Please run `prepare_deployment_data.py` locally first.")
        st.stop()
    
    df = pd.read_csv(DATA_PATH)
    
    # --- Data Cleaning for Visualization ---
    # Ensure Contract_Type exists (Default to 'Unknown' if missing to prevent crash)
    if "Contract_Type" not in df.columns:
        df["Contract_Type"] = "Free_Market" # Fallback assumption
    
    # Ensure Salary is numeric
    df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")
    
    return df

df = load_data()

# --- 2. PAGE CONTENT ---

st.title("Statistical vs. Deterministic Players")

st.markdown("""
Not every NBA salary is created the same way.

Some players are paid by **pure formula** – their contracts are locked in by league rules, not by what a team is willing to offer in an open negotiation. These are the **deterministic players**: rookies on the fixed Rookie Scale, stars on pre-defined Max deals, and veterans on minimum contracts. Their salaries are mostly decided before a single shot is taken.

Other players live in the **statistical world**. Their contracts are negotiated in the open market, where performance, timing, leverage, and perception all collide. These are the players our models can truly “listen to” when learning how the NBA values different skills and attributes.
""")

st.info("""
**Why this matters:** If we trained our model on everyone, the "Deterministic" players would confuse it. 
A rookie superstar like **Wembanyama** would look "underpaid," not because of bias, but because of the **Rookie Scale**. 
We must separate them to find the true market signal.
""")

st.markdown("---")

# --- 3. VISUALIZATION SECTION ---

st.header("Visualizing the Divide")
st.markdown("The scatter plot below separates the league by contract type. Notice the structural walls that constrain salaries.")

# User Controls
col1, col2 = st.columns([1, 3])
with col1:
    # Use metrics confirmed to exist in your dataset
    x_metric = st.selectbox(
        "Performance Metric (X-Axis)",
        options=["OFF_RATING", "NET_RATING", "PIE", "PTS", "PER"],
        index=2, # Default to PIE
        help="Select a metric to represent on-court performance."
    )

# Fallback if the selected metric isn't in the CSV
if x_metric not in df.columns:
    st.warning(f"Metric '{x_metric}' not found in data. Defaulting to 'Salary'.")
    x_metric = "Salary"

# --- SCATTER PLOT LOGIC ---
# Define colors for contract types
contract_colors = {
    "Free_Market": "#FFA500",   # Orange (The Signal)
    "Rookie_Scale": "#EF553B",  # Red (The Floor)
    "Max_Contract": "#636EFA",  # Blue (The Ceiling)
    "Minimum": "#00CC96",       # Green
    "Unknown": "#888888"
}

# Create Figure
fig = px.scatter(
    df,
    x=x_metric,
    y="Salary",
    color="Contract_Type",
    log_y=True, # Log scale is crucial for salary data
    hover_name="PLAYER_NAME",
    # FIXED: Changed "Team" to "TEAM_NAME"
    hover_data=["Age", "TEAM_NAME", "Contract_Type"],
    color_discrete_map=contract_colors,
    title=f"Salary vs. {x_metric} (Log Scale)",
    height=600
)

# --- ANNOTATIONS (Wemby vs Curry) ---
# We highlight specific players to tell the story
highlight_players = ["Victor Wembanyama", "Stephen Curry", "LeBron James"]

for player in highlight_players:
    player_row = df[df["PLAYER_NAME"] == player]
    if not player_row.empty:
        row = player_row.iloc[0]
        # Check if the x_metric exists for this player before annotating
        if pd.notna(row[x_metric]) and pd.notna(row["Salary"]):
            fig.add_annotation(
                x=row[x_metric],
                y=row["Salary"],
                text=f"<b>{player}</b>",
                showarrow=True,
                arrowhead=2,
                arrowsize=1,
                arrowwidth=2,
                arrowcolor="#333333",
                ax=0,
                ay=-40,
                bgcolor="#ffffff",
                opacity=0.9
            )

st.plotly_chart(fig, use_container_width=True)

st.markdown("""
### What to Look For:
1. **The "Free Market" Cloud (Orange):** Notice how these players form a rough diagonal line. As performance increases, salary increases. This is the "Statistical World."
2. **The Rookie Cluster (Red):** Even high performers (like Wembanyama) are pushed down structurally. Their pay is capped by their draft slot, not their stats.
3. **The Max Ceiling (Blue):** Superstars hit a hard ceiling. No matter how far right their performance goes, they cannot earn more than the max.
""")

st.markdown("---")

# --- 4. TEXT CONTENT ---

st.header("What Our Salary Data Lets Us See")

st.markdown("""
Our dataset combines:
- **Player salary** (how much they actually get paid),
- **On-court performance stats** (points, shooting, defense, impact metrics),
- **Contextual factors** like age, draft position, team market, and popularity signals.

By separating **deterministic contracts** from **free-market contracts**, we can learn how the market prices different skills *only* from players whose salaries are truly negotiable. We then **apply** those learned prices to everyone else to see where the system itself creates distortions.

### A Simple Question: Wemby vs. Curry

Take a thought experiment (visualized above):

- **Victor Wembanyama**: a young player who puts up elite defensive stats and warps the floor.
- **Stephen Curry**: a veteran whose shooting, gravity, and global popularity are off the charts.

On paper, you might ask: *"If Wemby has comparable impact metrics, why does Curry get paid so much more?"*

Our project doesn’t just say “because he’s a star.” We break that down into **measurable pieces**:
* How much is the **Age Premium**?
* How much is the **Rookie Scale Penalty**?
* How much is the **Popularity/Followers Boost**?

This allows us to move from "Curry gets paid more" to a data-driven map of **value, leverage, and structure**.
""")